spring:
  data:
    mongodb:
      database: testDB
      uri: ${MONGODB_URI}
  application:
    name: tourist-management-query-app
  jms:
    servicebus:
      connection-string: Endpoint=sb://yuva-fse-service-bus-namespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=DRhwlHiX2uTqIx/PlJBcTxvr9WmaKv+2j+ASbCy44HE=
      pricing-tier: basic
      receive-timeout: 50000
logging:
  level:
    root: INFO
    com.cognizant.fse.assignment: DEBUG
