spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testDB
  application:
    name: tourist-management-query-app

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  topic-name: tourist-companies

logging:
  level:
    root: INFO
    com.cognizant.fse.assignment: DEBUG

server:
  port: 8083
